# Generated by Django 3.0.6 on 2020-05-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designerprofile',
            old_name='designer_user',
            new_name='user',
        ),
    ]
