# Generated by Django 3.0.6 on 2020-05-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200510_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='first_name',
            field=models.CharField(default='temp', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='last_name',
            field=models.CharField(default='temp', max_length=30),
            preserve_default=False,
        ),
    ]
