# Generated by Django 3.0.6 on 2020-05-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200510_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='email',
            field=models.EmailField(default='temp', max_length=254),
            preserve_default=False,
        ),
    ]
