# Generated by Django 3.0.6 on 2020-05-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254, verbose_name='A few words about this work')),
                ('size', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Print',
            },
        ),
        migrations.AlterField(
            model_name='designer',
            name='bio',
            field=models.CharField(max_length=254, verbose_name='A few words about the designer'),
        ),
    ]
