# Generated by Django 3.0.6 on 2020-05-06 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_auto_20200506_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prints.Designer'),
        ),
    ]
