# Generated by Django 3.0.6 on 2020-05-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0004_auto_20200506_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prints',
            new_name='Print',
        ),
        migrations.AlterModelOptions(
            name='print',
            options={'verbose_name': 'Print'},
        ),
    ]
