# Generated by Django 3.0.6 on 2020-05-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
        ('prints', '0005_auto_20200506_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designers.Designers'),
        ),
        migrations.DeleteModel(
            name='Designer',
        ),
    ]
