# Generated by Django 3.0.6 on 2020-05-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=254, verbose_name='A few words about the designer')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Designer',
            },
        ),
    ]
